### ISSUE TITLE
CGo Pointer Errors

### ISSUE THREAD

**Issue by LegoRemix** [sjwhitworth/golearn#158]
Hello! I'm using this library to do Logistic Regression on some metadata signals from an internal system at my employer. However, I've run into the following panic : 
```bash
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/sjwhitworth/golearn/linear_models.Train.func1(0xc42049bc20, 0xc42727b280, 0x931f)
	/Users/babarin/code/src/github.com/sjwhitworth/golearn/linear_models/liblinear.go:61 +0xb3
github.com/sjwhitworth/golearn/linear_models.Train(0xc42049bc20, 0xc42727b280, 0x931f)
	/Users/babarin/code/src/github.com/sjwhitworth/golearn/linear_models/liblinear.go:61 +0x42
github.com/sjwhitworth/golearn/linear_models.(*LogisticRegression).Fit(0xc42731a040, 0x4243a40, 0xc42727b600, 0x4243a40, 0xc42727b600)
	/Users/babarin/code/src/github.com/sjwhitworth/golearn/linear_models/logistic.go:34 +0xd3
main.main()
	/Users/babarin/code/src/code.justin.tv/chat/classy/classifier/spam/learn/analyze.go:420 +0x944
exit status 2


---
```

I can bulldoze by this error by using GODEBUG=cgocheck=0,  but this isn't ideal.

**Comment by amclay** [comment]
Also running into this issue with go 1.8

**Comment by Sentimentron** [comment]
Yeah, this might require a bit of a design change, I'll do some investigation.

**Comment by Sentimentron** [comment]
Fix is coming in  #167, but I've managed to mess up the memory management 👎

**Comment by amclay** [comment]
@Sentimentron Do you have plans to support/revisit this at a later date still?

**Comment by rjzak** [comment]
Two years later, I'm getting the same issue.
