### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by luojh2015** [sjwhitworth/golearn#230]
https://github.com/sjwhitworth/golearn/blob/82e59c89f5020c45292c68472908f2150a87422e/linear_models/liblinear.go#L65

Line 21: - runtime error: cgo argument has Go pointer to Go pointer 
  goroutine 19 [running]:
  panic(0x8bc2e0, 0xc000045a50)
  	D:/Go/src/runtime/panic.go:513 +0x1f4
  github.com/sjwhitworth/golearn/linear_models.Train.func1(0xc00004bc20, 0xc0000e0ac0, 0x0)
  	D:/golang/src/github.com/sjwhitworth/golearn/linear_models/liblinear.go:65 +0x61

**Comment by luojh2015** [comment]
"GODEBUG": "cgocheck=0"Is there any other way

**Comment by luojh2015** [comment]
GODEBUG=cgocheck=0，Is there any other way?

**Comment by luojh2015** [comment]
https://github.com/sjwhitworth/golearn/pull/167/commits/5632e43237fcaf1babde835f66b8872591ba9fd2#diff-9c2cf5d36b356bede9639f41041e6613
